# Generated by Django 4.1.1 on 2022-12-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
